In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.ndim

1

In [7]:
arr2d=np.array([[1,2,3,4],[5,6,7,8]])
arr2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr2d.ndim

2

In [10]:
arr.size

4

In [9]:
arr2d.size

8

In [11]:
arr2d.shape

(2, 4)

In [12]:
arr2d.dtype

dtype('int64')

In [13]:
arr.dtype

dtype('int64')

In [15]:
mx=np.ones(5)
mx

array([1., 1., 1., 1., 1.])

In [16]:
mx.dtype

dtype('float64')

In [ ]:
mx = np.ones(3,4)
mx

In [18]:
mx = np.ones((3,4))
mx

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
np.zeros((5,6),dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [24]:
np.zeros((5,6),dtype=bool)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [25]:
np.zeros((5,6),dtype=str)

array([['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', '']], dtype='<U1')

In [26]:
emst = ''
bool(emst)

False

In [28]:
empty_mx = np.empty((4,5))
empty_mx

array([[2.60460183e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])

#arange

In [41]:
ar1=np.arange(2,20)
ar1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [31]:
np.arange(5,20,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

#linspace()

In [32]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [33]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

#reshape()

In [43]:
ar2 = ar1.reshape(3,6)
ar2

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19]])

In [46]:
ar3 = ar1.reshape(3,3,2)
ar3

array([[[ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17],
        [18, 19]]])

In [47]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

#ravel()

In [50]:
ar1.ravel()

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

#flatten()

In [66]:
ar1=np.arange(1,13).reshape(2,6)
ar1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [56]:
ar1.flatten()

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

ravel and flatten converts nd array into 1d array

In [65]:
ar1.flatten(order='C')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [53]:
ar1.flatten(order='F')

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [64]:
ar1.flatten(order='A')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#transpose()

In [67]:
ar1.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])